// USERS TYPES

export const FETCH_DATA_REQUEST_USER = "FETCH_DATA_REQUEST_USER";
export const FETCH_DATA_SUCCESS_USER = "FETCH_DATA_SUCCESS_USER";
export const FETCH_DATA_FAILURE_USER = "FETCH_DATA_FAILURE_USER";
export const REMOVE_ITEM_USER = "REMOVE_ITEM_USER";
export const UPDATE_USER_ACTION = "UPDATE_USER_ACTION";